name: Merge XML Test

on: workflow_dispatch

jobs:
  merge-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: List files before
      run: |
        echo "=== MERGE ÖNCESİ DOSYALAR ==="
        ls -la
        echo "=== XML DOSYALARI ==="
        find . -name "*.xml" -type f
        
    - name: Run merge script
      run: |
        python merge_xml.py
        echo "=== SCRIPT ÇIKTI KODU: $? ==="
        
    - name: List files after
      run: |
        echo "=== MERGE SONRASI DOSYALAR ==="
        ls -la
        echo "=== OLUŞAN DOSYA KONTROLÜ ==="
        if [ -f "merged.xml" ]; then
          echo "✅ merged.xml OLUŞTU"
          echo "=== DOSYA İÇERİĞİ ==="
          cat merged.xml
        else
          echo "❌ merged.xml OLUŞMADI"
        fi
        
    - name: Commit if file created
      run: |
        if [ -f "merged.xml" ]; then
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add merged.xml
          git commit -m "Add merged.xml"
          git push
          echo "✅ Commit yapıldı"
        else
          echo "❌ Commit yapılamadı - dosya yok"
        fi
