name: Merge XML Files

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  merge-xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Merge XML files
      run: python merge_xml.py
      
    - name: Commit and push
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "XML files merged" || exit 0
        git push
