name: Auto Merge XML Files

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  merge-xml-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Merge XML files
      run: python merge_xml.py
    - name: Commit changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Auto-merge XML" || exit 0
        git push
