name: Merge XML Lists

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Requests
      run: pip install requests

    - name: Merge XML Lists
      run: python merge_xml.py

    - name: Upload Combined XML as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-xml
        path: combined.xml
