name: Merge XML Lists

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Merge XML files
      run: python birles_xml.py

    - name: Force timestamp update (always commit)
      run: |
        echo "<!-- Updated: $(date) -->" >> combined.xml

    - name: Commit and Push Combined XML
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add combined.xml
        git commit -m "Auto-update: combined.xml ($(date))" || echo "No changes"
        git push
