name: Günlük YouTube Haber Güncelleme (Deneme)

on:
  workflow_dispatch:   # Elle çalıştırma
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  update-haber:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu çek
        uses: actions/checkout@v4

      - name: Python ortamını kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli kütüphaneleri yükle
        run: pip install requests xmltodict

      - name: XML dosyasını güncelle
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY_HABER }}
        run: python update_haber.py

      - name: Commit ve Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xml/haber.xml
          git diff-index --quiet HEAD || git commit -m "Haber listesi güncellendi"
          git push origin HEAD:main
